from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from django.urls import reverse
from .models import Lifafa, ScrapbookPage

# ==========================================
# SENDER VIEWS (LOGIN REQUIRED)
# ==========================================

@login_required
@never_cache
def enjoy(request):
    return render(request, 'customization/for-you.html')

@login_required
@never_cache
def celeb(request):
    return render(request, 'customization/only-for-you.html')

@never_cache
def save_data(request):
    if request.method == 'POST':
        # 1. Fetch text data matching the JavaScript FormData keys exactly
        heading = request.POST.get('main_heading', '')
        receiver = request.POST.get('letter_to', '')
        message = request.POST.get('letter_body', '')
        sender = request.POST.get('letter_from', '')

        # 2. Create the envelope in the database
        new_lifafa = Lifafa.objects.create(
            main_heading=heading,
            receiver_name=receiver,
            sender_name=sender,
            message=message
        )
        
        # 3. Loop through 8 blocks and save ScrapbookPages
        for i in range(1, 9):
            image_file = request.FILES.get(f'photo_{i}') 
            quote_text = request.POST.get(f'quote_{i}', '')
            
            if image_file or quote_text.strip():
                ScrapbookPage.objects.create(
                    lifafa=new_lifafa,
                    page_number=i,
                    image=image_file,
                    quote_text=quote_text
                )

        # 4. Grab the 8-character secret key generated by the database model
        generated_key = new_lifafa.secret_key

        # 5. Return success response to the frontend JS
        return JsonResponse({
            'success': True, 
            'message': 'Database successfully updated!',
            'secret_key': generated_key
        })

    return JsonResponse({'success': False, 'error': 'Invalid request method.'}, status=400)


# ==========================================
# RECEIVER VIEWS (NO LOGIN REQUIRED)
# ==========================================

@never_cache
def receiver_loading(request, secret_key):
    # Step 1: Validates the key exists before showing the animation
    get_object_or_404(Lifafa, secret_key=secret_key)
    # Renders your loading screen
    return render(request, 'account/loading.html', {'secret_key': secret_key})

@never_cache
def receiver_envelope(request, secret_key):
    # Step 2: Show the Envelope (for-you.html) in read-only mode
    lifafa = get_object_or_404(Lifafa, secret_key=secret_key)
    return render(request, 'customization/for-you.html', {
        'lifafa': lifafa,
        'secret_key': secret_key,
        'is_receiver_mode': True
    })

@never_cache
def receiver_scrapbook(request, secret_key):
    # Step 3: Show the Scrapbook (only-for-you.html) in read-only mode
    lifafa = get_object_or_404(Lifafa, secret_key=secret_key)
    
    pages = lifafa.pages.all()
    page_data = {}
    for page in pages:
        page_data[page.page_number] = page

    context = {
        'lifafa': lifafa,
        'page_data': page_data,
        'is_receiver_mode': True 
    }
    
    return render(request, 'customization/only-for-you.html', context)