# Generated by Django 6.1 on 2026-08-30 23:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lifafa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('main_heading', models.TextField(blank=True, null=True)),
                ('receiver_name', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('sender_name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='scrapbook_images/')),
                ('quote_text', models.TextField(blank=True, null=True)),
                ('lifafa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='data_proccess.lifafa')),
            ],
        ),
    ]
