# Generated by Django 6.1 on 2026-08-30 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_proccess', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lifafa',
            name='main_heading',
            field=models.TextField(blank=True, null=True),
        ),
    ]
